### ISSUE TITLE
install broken

### ISSUE THREAD

**Issue by betayi** [azerothcore/acore-cms#117]
after install from docker compose, login with admin account just created ,and active the plugin "AzerothCore Wordpress Integration", it tolds "This theme requires the following plugins: MyCred and WooCommerce.";

Install MyCred Shows:
Installing Plugin: MyCred
Downloading installation package from https://downloads.wordpress.org/plugin/mycred.2.4.7.zip…
Unpacking the package…
Could not create directory.

Install WooCommerce Shows:
 Installing Plugin: WooCommerce
Downloading installation package from https://downloads.wordpress.org/plugin/woocommerce.6.6.1.zip…
Unpacking the package…
Could not create directory.

So, this installation can not continue to next step.

**Comment by NicolaiMogensen** [comment]
Just go into the container, create the folders mycred and woocommerce, set their permissions to chmod 777. Now it works.

**Comment by Helias** [comment]
775 should work as well
