### ISSUE TITLE
Cash on delivery does not work correctly

### ISSUE THREAD

**Issue by Dr-Arayashiki** [azerothcore/acore-cms#126]
I discovered something, putting the payment method as "Payment on delivery", it does not send the item even if in the order status you put it as completed. 

It looks like the payment method verification has to be automatic to work and the item to be shipped

**Comment by Ercules76** [comment]
https://github.com/azerothcore/acore-cms/issues/12

**Comment by Helias** [comment]
I am closing this issue because it's a duplicate
