### ISSUE TITLE
 acore-cms在WINSVR上IIS 报错，数据库是空的

### ISSUE THREAD

**Issue by kasting** [azerothcore/acore-cms#127]
我是一个新手
我在IIS的虚拟目录指向了acore-cms\srv\wordpress目录
第一次运行显示
![微信图片_20230221152953](https://user-images.githubusercontent.com/83107774/220277527-4968db4a-c092-4e15-8ac3-e54dd0fbea13.png)
![微信图片_20230221153112](https://user-images.githubusercontent.com/83107774/220277544-f6d5b85a-da40-46af-868d-0d419ae45ea9.png)
就是说PHP调用是正常的
但是一旦调用数据库就会报错
PHP Fatal error:  Uncaught mysqli_sql_exception: Unknown column 'wp_' in 'field list' in E:\AZ\acore-cms\srv\wordpress\wp-includes\wp-db.php:2056
我是手动增加了wordpress数据库
然后手动修改了wp-config.php
然后报
PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'wordpress.wp_options' doesn't exist in E:\AZ\acore-cms\srv\wordpress\wp-includes\wp-db.php:2056
这说明我的数据库是空的，程序找不到数据库的各项表
我应该怎么做才能找到数据库正常的结构和值呢

**Comment by Helias** [comment]
If you are using the docker compose you do not need to create any wordpress database, if you are installing it manually you only need to create an empty database called "wordpress" and use the wordpress wizard setup to install it.
Anyways, this seems an issue related to wordpress not to the acore-cms itself, if you look around online you'll find several guides on how to install wordpress manually, afterward, you can add the acore-wp-plugin to you wordpress installation to have acore-cms.
