### ISSUE TITLE
WordPress 可以正常安装、运行，但是依旧无法安装 acore-cms，我应该从哪里获得acore-wp-plugin并安装呢

### ISSUE THREAD

**Issue by kasting** [azerothcore/acore-cms#128]
WordPress 可以正常安装、运行
![微信图片_20230223020008](https://user-images.githubusercontent.com/83107774/220715541-93e9b2c6-d906-4643-8e74-10ca1636bf99.png)
但是依旧无法安装 acore-cms
上次您提到可以安装WordPress 后
安装acore-wp-plugin
我应该在哪里获得acore-wp-plugin并安装呢

**Comment by gyzuike** [comment]
https://github.com/azerothcore/acore-cms/tree/master/srv/wordpress/wp-content/plugins，你看这里的能保存下来不
