### ISSUE TITLE
improve the password generator for WoW

### ISSUE THREAD

**Issue by Helias** [azerothcore/acore-cms#17]
We need to be careful about special characters

**Comment by masterking32** [comment]
> We need to be careful about special characters

I always allowed `A-Z 0-9 and -_.` but I think client can support more characters bcz they convert them to hash, You can use `$%^&@!#*()` too !

**Comment by 55Honey** [comment]
`? .`  are working, too.

**Comment by 55Honey** [comment]
We need to Limit the Password length to 16 characters and also prevent spaces.

**Comment by r-o-b-o-t-o** [comment]
I tested all the characters in the ASCII table from 32 to 126, and the only one that did not work was the pipe character (`|`), which when typed or pasted into the client gets transformed into two characters for some reason.

List of tested characters (without alphanumeric characters for brevity):
![image](https://user-images.githubusercontent.com/24357633/120901397-de9a7780-c63a-11eb-87f3-7e3323b722f5.png)

Also yes, limiting to 16 characters is a must.

**Comment by r-o-b-o-t-o** [comment]
Also note that characters from the extended ASCII table (128 and up) do not work at all in the client.

**Comment by Helias** [comment]
thank you :heart: 
About the length limit I already implemented it, I will try to filter these allowed characters.
I am not sure if the WoW client can't use the following accentuated letters àèéìòù, because I used it in Say a lot of times, anyway I'll do a test for the accentuated when I'll implement the filter

**Comment by r-o-b-o-t-o** [comment]
> I am not sure if the WoW client can't use the following accentuated letters àèéìòù, because I used it in Say a lot of times, anyway I'll do a test for the accentuated when I'll implement the filter

You're right, I tested again, this time by creating an account from the worldserver console and the accents work, the quick script I made to create accounts in a batch must have handled these characters incorrectly. Sorry about that!

**Comment by Helias** [comment]
no worries ;-)
