### ISSUE TITLE
getExpansion() error

### ISSUE THREAD

**Issue by Helias** [azerothcore/acore-cms#29]
```
Fatal error: Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Call to a member function getExpansion() on null in /var/www/html/wp-content/plugins/acore-wp-plugin/src/hooks/user/user.php:273
```
How to reproduce the bug:
- go to the Wordpress panel
- go to User -> create new User
- after creation of new user try to edit the User
- the new account will not have any WoW account created so it will through this error

temporary workaround -> log in with the user to create the game account

**Comment by nicoaravena** [comment]
Should be close by #49?

**Comment by Helias** [comment]
definitely, I did that for this issue but I forgot to close, thanks!
