### ISSUE TITLE
"Could not create directory." when installing required plugins.

### ISSUE THREAD

**Issue by BuildingOutLoud** [azerothcore/acore-cms#33]
I've installed acore-cms on Ubuntu 20.04. The docker comes up and I've set up my Wordpress administrator. When I activate AzerothCore Wordpress Integration it requires MyCred and WooCommerce plugins to be installed. When I try to install either of those I get the following:

Installing Plugin: MyCred

Downloading installation package from https://downloads.wordpress.org/plugin/mycred.2.0.2.zip…

Unpacking the package…

Could not create directory.

**Comment by Helias** [comment]
this should be solved recently. it was an issue of permissions
