### ISSUE TITLE
Feature request: Shop bills should clearly show the sent command

### ISSUE THREAD

**Issue by 55Honey** [azerothcore/acore-cms#35]
If a player requests a refund there is currently no way for level 1 support to determine if the request is valid. They can not check the shop bill for which item/service was purchased. If they knew the exact service, they could possibly tell, if the case requires an admins attention.

**Comment by FrancescoBorzi** [comment]
@Yehonal @Helias @nicoaravena

**Comment by IcemanHHW** [comment]
Picking this one up

**Comment by Helias** [comment]
when you do it, assign the issue to yourself by the github options 👍 

![image](https://user-images.githubusercontent.com/519778/161378542-7a99d7fe-7655-40a6-8d86-899749039a3c.png)

**Comment by IcemanHHW** [comment]
I think I'm not really understanding the ticket 😅 

Is it to make the meta data shown on the Order/Item info available to everyone that has access to the Orders
![afbeelding](https://user-images.githubusercontent.com/20383130/161380396-011c40e0-97ed-4519-8b3e-733f127c0fea.png)

Or to show that meta data on the order list in a new column?
![afbeelding](https://user-images.githubusercontent.com/20383130/161380420-0f13c217-ee89-4f1e-8115-0f50f2a8491e.png)

**Comment by 55Honey** [comment]
It's is to have the player see the exact command sent to the server in their receipt. 
So If they open a ticket and show us their receipt, we can also see what was supposed to be sent. Instead of asking for the Item and they answer wrong and we're looking for the wrong item/spell/service on their characters.

**Comment by Helias** [comment]
Writing the command next to the `SKU`, which is `itemsend_2846` for example.

So the player and any moderator can easily see it, like he already see the itemsend_XXXX.

To be sure that you understand, try locally to make a player account that have no rights and make a order, when the order is complete, be sure that the user receive the itemsend_XXXX (that he already receives) and also the related SOAP command

to avoid redudant code you could put all the commands in a dictionary or into an array and share it between this funciton that prints the command and the related services that uses the command

Hope it's clear, let me know in case if you need more details

**Comment by Helias** [comment]
nevermind, we've found another solution already implemented
