### ISSUE TITLE
Symfony may conflict

### ISSUE THREAD

**Issue by XiaoSeee** [azerothcore/acore-cms#42]
When I use [alipay plugin](https://github.com/xytoki/woocommerce-alipay-f2f), I will be prompted every time the payment is completed:
```cmd
PHP Fatal error:  Cannot declare class Symfony\Component\HttpFoundation\ParameterBag, because the name is already in use in /var/www/html/wp-content/plugins/acore-wp-plugin/var/bootstrap.php.cache on line 6
```

It seems to be a symfony conflict,

It will crash when `$WoWSrv = ACoreServices::I(); `
https://github.com/azerothcore/acore-cms/blob/497cc92c12c52f3455c3504bd8b6bedd34f78ea8/srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/item_send.php#L210-L212

I found that everything is normal when it is disabled `acore-wp-plugin/src/core/app.php line 11 `
https://github.com/azerothcore/acore-cms/blob/497cc92c12c52f3455c3504bd8b6bedd34f78ea8/srv/wordpress/wp-content/plugins/acore-wp-plugin/src/core/app.php#L8-L12
 I don't know what the impact is?

**Comment by Helias** [comment]
closed by https://github.com/azerothcore/acore-cms/pull/45
