### ISSUE TITLE
function name miss /

### ISSUE THREAD

**Issue by XiaoSeee** [azerothcore/acore-cms#43]
when in order details page
```cmd
PHP Warning:  call_user_func_array() expects parameter 1 to be a valid callback, function 'ACorewoo_display_order_username' not found or invalid function name in /var/www/html/wp-includes/class-wp-hook.php on line 292
```
https://github.com/azerothcore/acore-cms/blob/497cc92c12c52f3455c3504bd8b6bedd34f78ea8/srv/wordpress/wp-content/plugins/acore-wp-plugin/src/hooks/woocommerce/woocommerce.php#L15

miss `\` like this

```php
add_action('woocommerce_admin_order_data_after_billing_address', __NAMESPACE__ . '\woo_display_order_username', 10, 1);
```

**Comment by Helias** [comment]
closed by https://github.com/azerothcore/acore-cms/pull/45
