### ISSUE TITLE
character order

### ISSUE THREAD

**Issue by Helias** [azerothcore/acore-cms#53]
I can't see the "characters" section in an admin account :(

I should see it here.
![image](https://user-images.githubusercontent.com/519778/124829835-6d235100-df79-11eb-8f5a-cefd5764499f.png)

because I have no the "Profile" section as admin but "Users"

(as a normal user see it)
![image](https://user-images.githubusercontent.com/519778/124829937-875d2f00-df79-11eb-810b-162ad6c2e427.png)

**Comment by nicoaravena** [comment]
It is because is using the role name instead of the capability, should be `'read'` instead of `'subscriber'`.

**Comment by Helias** [comment]
so it's a configuration issue not related to the code implementation, right?

**Comment by nicoaravena** [comment]
Nope is code, I create a PR with the fix.
