### ISSUE TITLE
No buy interaction with Argent Dawn Quartermaster.

### ISSUE THREAD

**Issue by minthes** [azerothcore/acore-cms#82]
Despite being revered with the Argent Dawn, and not having "at war" box ticked, I do not see a buy interaction with the AD quartermaster. I can pick up the quests. I just don't have a buy interaction.
![WoWScrnShot_113021_091123](https://user-images.githubusercontent.com/94015041/144097026-e537c85a-1b15-4dbe-b5af-bf5b26a39200.jpg)
P

**Comment by Helias** [comment]
Hi, thanks for your report but this is not the right repository where you can report this kind of bugs, please open an issue [here](https://github.com/azerothcore/azerothcore-wotlk/issues/new/choose) in azerothcore/azerothcore-wotlk.
