### ISSUE TITLE
[Feature] Add Quest reset service

### ISSUE THREAD

**Issue by nicoaravena** [azerothcore/acore-cms#95]
Add quest reset service as a product or free for all (similar to item restoration #85 )
Proposal:
* Add a new option to enable Quest Reset service (FFA or as product).
* Add a wp-admin panel view for free for all.
* Use SKU `quest-reset` to add it as a store product.

**Comment by Helias** [comment]
added to the board https://github.com/orgs/chromiecraft/projects/5/views/21

**Comment by Helias** [comment]
Removed from board and closed as discussed.
