### ISSUE TITLE
[UI improvement] improve char selection UI in shop services 

### ISSUE THREAD

**Issue by Helias** [azerothcore/acore-cms#96]
"I suggest moving the char selection part in between quantity and "add to basket" buttons and giving it the same black bg with white border for better visibility.
But in case there is no other expert like me that was able to get a service on a wrong char in past, maybe it's ok 😄"
**by user Valjean**

![image](https://user-images.githubusercontent.com/519778/156880192-c18a01ed-e26b-4fe8-b266-7ff491a6f8e3.png)

About the style we do not need to implement it in acore-cms but inside chromiecraft-cms in a separate PR/repo so I would say to ignore it for now, because it depends in the theme that the user is using, so let use a standard style that can fit multiple themes.

I would like to show the characters like we already show them in "Character orders", so re-using the images that we already have inside acore-cms.

![image](https://user-images.githubusercontent.com/519778/156880297-3038d626-52bd-4074-bc3b-f51c82bbf71c.png)

**Comment by gettheboom** [comment]
display: block;?

**Comment by Helias** [comment]
if you want to experiment any CSS code I strongly recommend you to use the built-in tool of the browser and change the CSS there, later I recommend to implement the CSS code inside acore-cms (acore-cms/srv/wordpress/wp-content/plugins/acore-wp-plugin/) and make a PR, there me and Dalanth (@nicoaravena) we'll review your PR and suggest you how to improve the code quality.

Personally, I don't mind if you use display block or other solutions, let's try it first and later make a PR 👍

**Comment by IcemanHHW** [comment]
will pick this up to get a better feel with the CMS

**Comment by Helias** [comment]
closed by https://github.com/azerothcore/acore-cms/pull/104
